server {
    listen 80;

    location /douyin {
        proxy_pass http://douyin_tiktok_download_api:8999/api/v1/douyin/web/fetch_user_live_videos;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}