server {
    listen 80;

    # 使用 web_rid 获取直播间信息
    location /douyin {
        proxy_pass http://172.17.0.1:8999/api/douyin/web/fetch_user_live_videos;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 通过分享链接获取 web_rid / room_id (可能返回web_rid，可能返回 room_id)
    location /douyin-share {
        proxy_pass http://172.17.0.1:8999/api/douyin/web/get_webcast_id;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 使用 room-id 获取直播间信息
    location /douyin-room_id {
        proxy_pass http://172.17.0.1:8999/api/douyin/web/fetch_user_live_videos_by_room_id;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}