server {
    listen 80;

    location /douyin {
        proxy_pass http://172.17.0.1:8999/api/douyin/web/fetch_user_live_videos;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /douyin-share {
        proxy_pass http://172.17.0.1:8999/api/douyin/web/get_webcast_id;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}